# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

points_within2 <- function(x_R, se_R, fi_R, return_list_R, return_unique_R, return_point_counts_R) {
    .Call('_Regionvelocity_points_within2', PACKAGE = 'Regionvelocity', x_R, se_R, fi_R, return_list_R, return_unique_R, return_point_counts_R)
}

balanced_knn <- function(d, k, maxl, returnDistanceValues = FALSE, nthreads = 1L) {
    .Call('_Regionvelocity_balanced_knn', PACKAGE = 'Regionvelocity', d, k, maxl, returnDistanceValues, nthreads)
}

arma_mat_cor <- function(m) {
    .Call('_Regionvelocity_arma_mat_cor', PACKAGE = 'Regionvelocity', m)
}

colDeltaCor <- function(e, d, nthreads = 1L) {
    .Call('_Regionvelocity_colDeltaCor', PACKAGE = 'Regionvelocity', e, d, nthreads)
}

colDeltaCorSqrt <- function(e, d, nthreads = 1L) {
    .Call('_Regionvelocity_colDeltaCorSqrt', PACKAGE = 'Regionvelocity', e, d, nthreads)
}

colDeltaCorLog10 <- function(e, d, pseudocount = 1.0, nthreads = 1L) {
    .Call('_Regionvelocity_colDeltaCorLog10', PACKAGE = 'Regionvelocity', e, d, pseudocount, nthreads)
}

colEuclid <- function(e, p, nthreads = 1L) {
    .Call('_Regionvelocity_colEuclid', PACKAGE = 'Regionvelocity', e, p, nthreads)
}

embArrows <- function(emb, tp, arrowScale = 1.0, nthreads = 1L) {
    .Call('_Regionvelocity_embArrows', PACKAGE = 'Regionvelocity', emb, tp, arrowScale, nthreads)
}

expectedExpressionShift <- function(e, tp, scale = 1L, pseudocount = 1.0, nthreads = 1L) {
    .Call('_Regionvelocity_expectedExpressionShift', PACKAGE = 'Regionvelocity', e, tp, scale, pseudocount, nthreads)
}

flatLength <- function(m) {
    .Call('_Regionvelocity_flatLength', PACKAGE = 'Regionvelocity', m)
}

groupMotifs <- function(df, msize = 1L) {
    .Call('_Regionvelocity_groupMotifs', PACKAGE = 'Regionvelocity', df, msize)
}

